//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.20 at 03:53:34 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datacite.org/schema/kernel-2.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.edu.aekos.shared.doiclient.jaxb;
