//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for citationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="citationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="fullCitation">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="citationMetadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="identifier" type="{http://ands.org.au/standards/rif-cs/registryObjects}identifierType"/>
 *                   &lt;element name="contributor" type="{http://ands.org.au/standards/rif-cs/registryObjects}citationNameType" maxOccurs="unbounded"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="placePublished" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="date" type="{http://ands.org.au/standards/rif-cs/registryObjects}citationDateType" maxOccurs="unbounded"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="context" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "citationInfoType", propOrder = {
    "fullCitation",
    "citationMetadata"
})
public class CitationInfoType {

    protected CitationInfoType.FullCitation fullCitation;
    protected CitationInfoType.CitationMetadata citationMetadata;

    /**
     * Gets the value of the fullCitation property.
     * 
     * @return
     *     possible object is
     *     {@link CitationInfoType.FullCitation }
     *     
     */
    public CitationInfoType.FullCitation getFullCitation() {
        return fullCitation;
    }

    /**
     * Sets the value of the fullCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationInfoType.FullCitation }
     *     
     */
    public void setFullCitation(CitationInfoType.FullCitation value) {
        this.fullCitation = value;
    }

    /**
     * Gets the value of the citationMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link CitationInfoType.CitationMetadata }
     *     
     */
    public CitationInfoType.CitationMetadata getCitationMetadata() {
        return citationMetadata;
    }

    /**
     * Sets the value of the citationMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationInfoType.CitationMetadata }
     *     
     */
    public void setCitationMetadata(CitationInfoType.CitationMetadata value) {
        this.citationMetadata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="identifier" type="{http://ands.org.au/standards/rif-cs/registryObjects}identifierType"/>
     *         &lt;element name="contributor" type="{http://ands.org.au/standards/rif-cs/registryObjects}citationNameType" maxOccurs="unbounded"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="placePublished" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="date" type="{http://ands.org.au/standards/rif-cs/registryObjects}citationDateType" maxOccurs="unbounded"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="context" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifierOrContributorOrTitle"
    })
    public static class CitationMetadata {

        @XmlElementRefs({
            @XmlElementRef(name = "placePublished", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "date", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "publisher", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "context", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "contributor", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "version", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "title", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "identifier", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "url", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "edition", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> identifierOrContributorOrTitle;

        /**
         * Gets the value of the identifierOrContributorOrTitle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the identifierOrContributorOrTitle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIdentifierOrContributorOrTitle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link CitationDateType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link CitationNameType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getIdentifierOrContributorOrTitle() {
            if (identifierOrContributorOrTitle == null) {
                identifierOrContributorOrTitle = new ArrayList<JAXBElement<?>>();
            }
            return this.identifierOrContributorOrTitle;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FullCitation {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "style")
        protected String style;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the style property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStyle() {
            return style;
        }

        /**
         * Sets the value of the style property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStyle(String value) {
            this.style = value;
        }

    }

}
