//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="identifier" type="{http://ands.org.au/standards/rif-cs/registryObjects}identifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="name" type="{http://ands.org.au/standards/rif-cs/registryObjects}nameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dates" type="{http://ands.org.au/standards/rif-cs/registryObjects}datesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="location" type="{http://ands.org.au/standards/rif-cs/registryObjects}locationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coverage" type="{http://ands.org.au/standards/rif-cs/registryObjects}coverageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="relatedObject" type="{http://ands.org.au/standards/rif-cs/registryObjects}relatedObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subject" type="{http://ands.org.au/standards/rif-cs/registryObjects}subjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://ands.org.au/standards/rif-cs/registryObjects}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rights" type="{http://ands.org.au/standards/rif-cs/registryObjects}rightsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="relatedInfo" type="{http://ands.org.au/standards/rif-cs/registryObjects}relatedInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="citationInfo" type="{http://ands.org.au/standards/rif-cs/registryObjects}citationInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://ands.org.au/standards/rif-cs/registryObjects}objectAttributes"/>
 *       &lt;attGroup ref="{http://ands.org.au/standards/rif-cs/registryObjects}collectionAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifierOrNameOrDates"
})
@XmlRootElement(name = "collection")
public class Collection {

    @XmlElements({
        @XmlElement(name = "identifier", type = IdentifierType.class),
        @XmlElement(name = "name", type = NameType.class),
        @XmlElement(name = "dates", type = DatesType.class),
        @XmlElement(name = "location", type = LocationType.class),
        @XmlElement(name = "coverage", type = CoverageType.class),
        @XmlElement(name = "relatedObject", type = RelatedObjectType.class),
        @XmlElement(name = "subject", type = SubjectType.class),
        @XmlElement(name = "description", type = DescriptionType.class),
        @XmlElement(name = "rights", type = RightsType.class),
        @XmlElement(name = "relatedInfo", type = RelatedInfoType.class),
        @XmlElement(name = "citationInfo", type = CitationInfoType.class)
    })
    protected List<Object> identifierOrNameOrDates;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "dateModified")
    protected String dateModified;
    @XmlAttribute(name = "dateAccessioned")
    protected String dateAccessioned;

    /**
     * Gets the value of the identifierOrNameOrDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifierOrNameOrDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifierOrNameOrDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * {@link NameType }
     * {@link DatesType }
     * {@link LocationType }
     * {@link CoverageType }
     * {@link RelatedObjectType }
     * {@link SubjectType }
     * {@link DescriptionType }
     * {@link RightsType }
     * {@link RelatedInfoType }
     * {@link CitationInfoType }
     * 
     * 
     */
    public List<Object> getIdentifierOrNameOrDates() {
        if (identifierOrNameOrDates == null) {
            identifierOrNameOrDates = new ArrayList<Object>();
        }
        return this.identifierOrNameOrDates;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the dateModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateModified() {
        return dateModified;
    }

    /**
     * Sets the value of the dateModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateModified(String value) {
        this.dateModified = value;
    }

    /**
     * Gets the value of the dateAccessioned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAccessioned() {
        return dateAccessioned;
    }

    /**
     * Sets the value of the dateAccessioned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAccessioned(String value) {
        this.dateAccessioned = value;
    }

}
