//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coverageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coverageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="spatial" type="{http://ands.org.au/standards/rif-cs/registryObjects}spatialType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="temporal" type="{http://ands.org.au/standards/rif-cs/registryObjects}temporalType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coverageType", propOrder = {
    "spatialOrTemporal"
})
public class CoverageType {

    @XmlElements({
        @XmlElement(name = "spatial", type = SpatialType.class),
        @XmlElement(name = "temporal", type = TemporalType.class)
    })
    protected List<Object> spatialOrTemporal;

    /**
     * Gets the value of the spatialOrTemporal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatialOrTemporal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpatialOrTemporal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpatialType }
     * {@link TemporalType }
     * 
     * 
     */
    public List<Object> getSpatialOrTemporal() {
        if (spatialOrTemporal == null) {
            spatialOrTemporal = new ArrayList<Object>();
        }
        return this.spatialOrTemporal;
    }

}
