//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * The location element can hold physical and/or electronic addresses as
 *                 well as geographical references. Use the <address> element for physical or
 *                 electronic address and the <spatial> element for geographical references. An
 *                 electronic address could be a website containing details about the activity or email
 *                 address whereas physical addresses can be provided for snail mail, billing,
 *                 enquiries. Physical addresses are split into parts should a more granular division
 *                 of address be required.
 * 
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="address" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="electronic" type="{http://ands.org.au/standards/rif-cs/registryObjects}electronicAddressType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="physical" type="{http://ands.org.au/standards/rif-cs/registryObjects}physicalAddressType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="spatial" type="{http://ands.org.au/standards/rif-cs/registryObjects}spatialType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ands.org.au/standards/rif-cs/registryObjects}dateRangeAttributes"/>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType", propOrder = {
    "address",
    "spatial"
})
public class LocationType {

    protected List<LocationType.Address> address;
    protected List<SpatialType> spatial;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "dateFrom")
    protected String dateFrom;
    @XmlAttribute(name = "dateTo")
    protected String dateTo;

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType.Address }
     * 
     * 
     */
    public List<LocationType.Address> getAddress() {
        if (address == null) {
            address = new ArrayList<LocationType.Address>();
        }
        return this.address;
    }

    /**
     * Gets the value of the spatial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpatial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpatialType }
     * 
     * 
     */
    public List<SpatialType> getSpatial() {
        if (spatial == null) {
            spatial = new ArrayList<SpatialType>();
        }
        return this.spatial;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the dateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFrom(String value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTo(String value) {
        this.dateTo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="electronic" type="{http://ands.org.au/standards/rif-cs/registryObjects}electronicAddressType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="physical" type="{http://ands.org.au/standards/rif-cs/registryObjects}physicalAddressType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "electronicOrPhysical"
    })
    public static class Address {

        @XmlElements({
            @XmlElement(name = "electronic", type = ElectronicAddressType.class),
            @XmlElement(name = "physical", type = PhysicalAddressType.class)
        })
        protected List<Object> electronicOrPhysical;

        /**
         * Gets the value of the electronicOrPhysical property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the electronicOrPhysical property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElectronicOrPhysical().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ElectronicAddressType }
         * {@link PhysicalAddressType }
         * 
         * 
         */
        public List<Object> getElectronicOrPhysical() {
            if (electronicOrPhysical == null) {
                electronicOrPhysical = new ArrayList<Object>();
            }
            return this.electronicOrPhysical;
        }

    }

}
