//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.org.ecoinformatics.rifcs.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Annotations_QNAME = new QName("http://ands.org.au/standards/rif-cs/extendedRegistryObjects", "annotations");
    private final static QName _RightsTypeRightsStatement_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "rightsStatement");
    private final static QName _RightsTypeLicence_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "licence");
    private final static QName _RightsTypeAccessRights_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "accessRights");
    private final static QName _RelatedInfoTypeNotes_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "notes");
    private final static QName _RelatedInfoTypeIdentifier_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "identifier");
    private final static QName _RelatedInfoTypeRelation_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "relation");
    private final static QName _RelatedInfoTypeFormat_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "format");
    private final static QName _RelatedInfoTypeTitle_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "title");
    private final static QName _CitationInfoTypeCitationMetadataDate_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "date");
    private final static QName _CitationInfoTypeCitationMetadataUrl_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "url");
    private final static QName _CitationInfoTypeCitationMetadataPublisher_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "publisher");
    private final static QName _CitationInfoTypeCitationMetadataVersion_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "version");
    private final static QName _CitationInfoTypeCitationMetadataContext_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "context");
    private final static QName _CitationInfoTypeCitationMetadataPlacePublished_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "placePublished");
    private final static QName _CitationInfoTypeCitationMetadataContributor_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "contributor");
    private final static QName _CitationInfoTypeCitationMetadataEdition_QNAME = new QName("http://ands.org.au/standards/rif-cs/registryObjects", "edition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.org.ecoinformatics.rifcs.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistryObjects }
     * 
     */
    public RegistryObjects createRegistryObjects() {
        return new RegistryObjects();
    }

    /**
     * Create an instance of {@link PhysicalAddressType }
     * 
     */
    public PhysicalAddressType createPhysicalAddressType() {
        return new PhysicalAddressType();
    }

    /**
     * Create an instance of {@link ElectronicAddressType }
     * 
     */
    public ElectronicAddressType createElectronicAddressType() {
        return new ElectronicAddressType();
    }

    /**
     * Create an instance of {@link TemporalType }
     * 
     */
    public TemporalType createTemporalType() {
        return new TemporalType();
    }

    /**
     * Create an instance of {@link RelatedInfoFormatType }
     * 
     */
    public RelatedInfoFormatType createRelatedInfoFormatType() {
        return new RelatedInfoFormatType();
    }

    /**
     * Create an instance of {@link CitationNameType }
     * 
     */
    public CitationNameType createCitationNameType() {
        return new CitationNameType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link CitationInfoType }
     * 
     */
    public CitationInfoType createCitationInfoType() {
        return new CitationInfoType();
    }

    /**
     * Create an instance of {@link DatesType }
     * 
     */
    public DatesType createDatesType() {
        return new DatesType();
    }

    /**
     * Create an instance of {@link RegistryObjects.RegistryObject }
     * 
     */
    public RegistryObjects.RegistryObject createRegistryObjectsRegistryObject() {
        return new RegistryObjects.RegistryObject();
    }

    /**
     * Create an instance of {@link ExistenceDateType }
     * 
     */
    public ExistenceDateType createExistenceDateType() {
        return new ExistenceDateType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link CoverageType }
     * 
     */
    public CoverageType createCoverageType() {
        return new CoverageType();
    }

    /**
     * Create an instance of {@link RelatedObjectType }
     * 
     */
    public RelatedObjectType createRelatedObjectType() {
        return new RelatedObjectType();
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link RightsType }
     * 
     */
    public RightsType createRightsType() {
        return new RightsType();
    }

    /**
     * Create an instance of {@link RelatedInfoType }
     * 
     */
    public RelatedInfoType createRelatedInfoType() {
        return new RelatedInfoType();
    }

    /**
     * Create an instance of {@link Collection }
     * 
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link RightsTypedInfoType }
     * 
     */
    public RightsTypedInfoType createRightsTypedInfoType() {
        return new RightsTypedInfoType();
    }

    /**
     * Create an instance of {@link RightsInfoType }
     * 
     */
    public RightsInfoType createRightsInfoType() {
        return new RightsInfoType();
    }

    /**
     * Create an instance of {@link SpatialType }
     * 
     */
    public SpatialType createSpatialType() {
        return new SpatialType();
    }

    /**
     * Create an instance of {@link CitationDateType }
     * 
     */
    public CitationDateType createCitationDateType() {
        return new CitationDateType();
    }

    /**
     * Create an instance of {@link AnnotationType }
     * 
     */
    public AnnotationType createAnnotationType() {
        return new AnnotationType();
    }

    /**
     * Create an instance of {@link PhysicalAddressType.AddressPart }
     * 
     */
    public PhysicalAddressType.AddressPart createPhysicalAddressTypeAddressPart() {
        return new PhysicalAddressType.AddressPart();
    }

    /**
     * Create an instance of {@link ElectronicAddressType.Arg }
     * 
     */
    public ElectronicAddressType.Arg createElectronicAddressTypeArg() {
        return new ElectronicAddressType.Arg();
    }

    /**
     * Create an instance of {@link TemporalType.Date }
     * 
     */
    public TemporalType.Date createTemporalTypeDate() {
        return new TemporalType.Date();
    }

    /**
     * Create an instance of {@link RelatedInfoFormatType.Identifier }
     * 
     */
    public RelatedInfoFormatType.Identifier createRelatedInfoFormatTypeIdentifier() {
        return new RelatedInfoFormatType.Identifier();
    }

    /**
     * Create an instance of {@link CitationNameType.NamePart }
     * 
     */
    public CitationNameType.NamePart createCitationNameTypeNamePart() {
        return new CitationNameType.NamePart();
    }

    /**
     * Create an instance of {@link RelationType.Description }
     * 
     */
    public RelationType.Description createRelationTypeDescription() {
        return new RelationType.Description();
    }

    /**
     * Create an instance of {@link CitationInfoType.FullCitation }
     * 
     */
    public CitationInfoType.FullCitation createCitationInfoTypeFullCitation() {
        return new CitationInfoType.FullCitation();
    }

    /**
     * Create an instance of {@link CitationInfoType.CitationMetadata }
     * 
     */
    public CitationInfoType.CitationMetadata createCitationInfoTypeCitationMetadata() {
        return new CitationInfoType.CitationMetadata();
    }

    /**
     * Create an instance of {@link DatesType.Date }
     * 
     */
    public DatesType.Date createDatesTypeDate() {
        return new DatesType.Date();
    }

    /**
     * Create an instance of {@link RegistryObjects.RegistryObject.OriginatingSource }
     * 
     */
    public RegistryObjects.RegistryObject.OriginatingSource createRegistryObjectsRegistryObjectOriginatingSource() {
        return new RegistryObjects.RegistryObject.OriginatingSource();
    }

    /**
     * Create an instance of {@link ExistenceDateType.StartDate }
     * 
     */
    public ExistenceDateType.StartDate createExistenceDateTypeStartDate() {
        return new ExistenceDateType.StartDate();
    }

    /**
     * Create an instance of {@link ExistenceDateType.EndDate }
     * 
     */
    public ExistenceDateType.EndDate createExistenceDateTypeEndDate() {
        return new ExistenceDateType.EndDate();
    }

    /**
     * Create an instance of {@link LocationType.Address }
     * 
     */
    public LocationType.Address createLocationTypeAddress() {
        return new LocationType.Address();
    }

    /**
     * Create an instance of {@link NameType.NamePart }
     * 
     */
    public NameType.NamePart createNameTypeNamePart() {
        return new NameType.NamePart();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/extendedRegistryObjects", name = "annotations")
    public JAXBElement<AnnotationType> createAnnotations(AnnotationType value) {
        return new JAXBElement<AnnotationType>(_Annotations_QNAME, AnnotationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RightsInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "rightsStatement", scope = RightsType.class)
    public JAXBElement<RightsInfoType> createRightsTypeRightsStatement(RightsInfoType value) {
        return new JAXBElement<RightsInfoType>(_RightsTypeRightsStatement_QNAME, RightsInfoType.class, RightsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RightsTypedInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "licence", scope = RightsType.class)
    public JAXBElement<RightsTypedInfoType> createRightsTypeLicence(RightsTypedInfoType value) {
        return new JAXBElement<RightsTypedInfoType>(_RightsTypeLicence_QNAME, RightsTypedInfoType.class, RightsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RightsTypedInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "accessRights", scope = RightsType.class)
    public JAXBElement<RightsTypedInfoType> createRightsTypeAccessRights(RightsTypedInfoType value) {
        return new JAXBElement<RightsTypedInfoType>(_RightsTypeAccessRights_QNAME, RightsTypedInfoType.class, RightsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "notes", scope = RelatedInfoType.class)
    public JAXBElement<String> createRelatedInfoTypeNotes(String value) {
        return new JAXBElement<String>(_RelatedInfoTypeNotes_QNAME, String.class, RelatedInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "identifier", scope = RelatedInfoType.class)
    public JAXBElement<IdentifierType> createRelatedInfoTypeIdentifier(IdentifierType value) {
        return new JAXBElement<IdentifierType>(_RelatedInfoTypeIdentifier_QNAME, IdentifierType.class, RelatedInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "relation", scope = RelatedInfoType.class)
    public JAXBElement<RelationType> createRelatedInfoTypeRelation(RelationType value) {
        return new JAXBElement<RelationType>(_RelatedInfoTypeRelation_QNAME, RelationType.class, RelatedInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedInfoFormatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "format", scope = RelatedInfoType.class)
    public JAXBElement<RelatedInfoFormatType> createRelatedInfoTypeFormat(RelatedInfoFormatType value) {
        return new JAXBElement<RelatedInfoFormatType>(_RelatedInfoTypeFormat_QNAME, RelatedInfoFormatType.class, RelatedInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "title", scope = RelatedInfoType.class)
    public JAXBElement<String> createRelatedInfoTypeTitle(String value) {
        return new JAXBElement<String>(_RelatedInfoTypeTitle_QNAME, String.class, RelatedInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "date", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<CitationDateType> createCitationInfoTypeCitationMetadataDate(CitationDateType value) {
        return new JAXBElement<CitationDateType>(_CitationInfoTypeCitationMetadataDate_QNAME, CitationDateType.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "identifier", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<IdentifierType> createCitationInfoTypeCitationMetadataIdentifier(IdentifierType value) {
        return new JAXBElement<IdentifierType>(_RelatedInfoTypeIdentifier_QNAME, IdentifierType.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "url", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataUrl(String value) {
        return new JAXBElement<String>(_CitationInfoTypeCitationMetadataUrl_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "publisher", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataPublisher(String value) {
        return new JAXBElement<String>(_CitationInfoTypeCitationMetadataPublisher_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "version", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataVersion(String value) {
        return new JAXBElement<String>(_CitationInfoTypeCitationMetadataVersion_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "context", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataContext(String value) {
        return new JAXBElement<String>(_CitationInfoTypeCitationMetadataContext_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "placePublished", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataPlacePublished(String value) {
        return new JAXBElement<String>(_CitationInfoTypeCitationMetadataPlacePublished_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "contributor", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<CitationNameType> createCitationInfoTypeCitationMetadataContributor(CitationNameType value) {
        return new JAXBElement<CitationNameType>(_CitationInfoTypeCitationMetadataContributor_QNAME, CitationNameType.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "edition", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataEdition(String value) {
        return new JAXBElement<String>(_CitationInfoTypeCitationMetadataEdition_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ands.org.au/standards/rif-cs/registryObjects", name = "title", scope = CitationInfoType.CitationMetadata.class)
    public JAXBElement<String> createCitationInfoTypeCitationMetadataTitle(String value) {
        return new JAXBElement<String>(_RelatedInfoTypeTitle_QNAME, String.class, CitationInfoType.CitationMetadata.class, value);
    }

}
