//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="registryObject" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="originatingSource">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;choice>
 *                     &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}activity"/>
 *                     &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}collection"/>
 *                     &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}party"/>
 *                     &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}service"/>
 *                   &lt;/choice>
 *                   &lt;element ref="{http://ands.org.au/standards/rif-cs/extendedRegistryObjects}annotations" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://ands.org.au/standards/rif-cs/registryObjects}registryObjectAttributes"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registryObject"
})
@XmlRootElement(name = "registryObjects")
public class RegistryObjects {

    protected List<RegistryObjects.RegistryObject> registryObject;

    /**
     * Gets the value of the registryObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the registryObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegistryObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegistryObjects.RegistryObject }
     * 
     * 
     */
    public List<RegistryObjects.RegistryObject> getRegistryObject() {
        if (registryObject == null) {
            registryObject = new ArrayList<RegistryObjects.RegistryObject>();
        }
        return this.registryObject;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="originatingSource">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;choice>
     *           &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}activity"/>
     *           &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}collection"/>
     *           &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}party"/>
     *           &lt;element ref="{http://ands.org.au/standards/rif-cs/registryObjects}service"/>
     *         &lt;/choice>
     *         &lt;element ref="{http://ands.org.au/standards/rif-cs/extendedRegistryObjects}annotations" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://ands.org.au/standards/rif-cs/registryObjects}registryObjectAttributes"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "key",
        "originatingSource",
        "activity",
        "collection",
        "party",
        "service",
        "annotations"
    })
    public static class RegistryObject {

        @XmlElement(required = true)
        protected String key;
        @XmlElement(required = true)
        protected RegistryObjects.RegistryObject.OriginatingSource originatingSource;
        protected Activity activity;
        protected Collection collection;
        protected Party party;
        protected Service service;
        @XmlElement(namespace = "http://ands.org.au/standards/rif-cs/extendedRegistryObjects")
        protected AnnotationType annotations;
        @XmlAttribute(name = "group", required = true)
        protected String group;

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKey(String value) {
            this.key = value;
        }

        /**
         * Gets the value of the originatingSource property.
         * 
         * @return
         *     possible object is
         *     {@link RegistryObjects.RegistryObject.OriginatingSource }
         *     
         */
        public RegistryObjects.RegistryObject.OriginatingSource getOriginatingSource() {
            return originatingSource;
        }

        /**
         * Sets the value of the originatingSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link RegistryObjects.RegistryObject.OriginatingSource }
         *     
         */
        public void setOriginatingSource(RegistryObjects.RegistryObject.OriginatingSource value) {
            this.originatingSource = value;
        }

        /**
         * Gets the value of the activity property.
         * 
         * @return
         *     possible object is
         *     {@link Activity }
         *     
         */
        public Activity getActivity() {
            return activity;
        }

        /**
         * Sets the value of the activity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Activity }
         *     
         */
        public void setActivity(Activity value) {
            this.activity = value;
        }

        /**
         * Gets the value of the collection property.
         * 
         * @return
         *     possible object is
         *     {@link Collection }
         *     
         */
        public Collection getCollection() {
            return collection;
        }

        /**
         * Sets the value of the collection property.
         * 
         * @param value
         *     allowed object is
         *     {@link Collection }
         *     
         */
        public void setCollection(Collection value) {
            this.collection = value;
        }

        /**
         * Gets the value of the party property.
         * 
         * @return
         *     possible object is
         *     {@link Party }
         *     
         */
        public Party getParty() {
            return party;
        }

        /**
         * Sets the value of the party property.
         * 
         * @param value
         *     allowed object is
         *     {@link Party }
         *     
         */
        public void setParty(Party value) {
            this.party = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link Service }
         *     
         */
        public Service getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link Service }
         *     
         */
        public void setService(Service value) {
            this.service = value;
        }

        /**
         * Gets the value of the annotations property.
         * 
         * @return
         *     possible object is
         *     {@link AnnotationType }
         *     
         */
        public AnnotationType getAnnotations() {
            return annotations;
        }

        /**
         * Sets the value of the annotations property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnotationType }
         *     
         */
        public void setAnnotations(AnnotationType value) {
            this.annotations = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroup(String value) {
            this.group = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class OriginatingSource {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }

}
