//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.24 at 05:12:04 PM CST 
//


package au.org.ecoinformatics.rifcs.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relatedInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relatedInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="identifier" type="{http://ands.org.au/standards/rif-cs/registryObjects}identifierType" maxOccurs="unbounded"/>
 *         &lt;element name="relation" type="{http://ands.org.au/standards/rif-cs/registryObjects}relationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="format" type="{http://ands.org.au/standards/rif-cs/registryObjects}relatedInfoFormatType" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedInfoType", propOrder = {
    "identifierOrRelationOrTitle"
})
public class RelatedInfoType {

    @XmlElementRefs({
        @XmlElementRef(name = "format", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "notes", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "relation", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "identifier", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", namespace = "http://ands.org.au/standards/rif-cs/registryObjects", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> identifierOrRelationOrTitle;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the identifierOrRelationOrTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifierOrRelationOrTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifierOrRelationOrTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link RelationType }{@code >}
     * {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link RelatedInfoFormatType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getIdentifierOrRelationOrTitle() {
        if (identifierOrRelationOrTitle == null) {
            identifierOrRelationOrTitle = new ArrayList<JAXBElement<?>>();
        }
        return this.identifierOrRelationOrTitle;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
