package au.org.ecoinformatics.rifcs.vocabs;

public enum CollectionTypeEnum {
	
	CATALOGUE_OR_INDEX("catalogueOrIndex","collection of resource descriptions describing the content of one or more repositories or collective works"),
	COLLECTION("collection","compiled content created as separate and independent works and assembled into a collective whole for distribution and use"),
	REGISTRY("registry","collection of registry objects compiled to support the business of a given community"),
	REPOSITORY("repository","collection of physical or digital objects compiled for information and documentation purposes and/or for storage and safekeeping"),
	DATASET("dataset","collection of physical or digital objects generated by research activities");

	CollectionTypeEnum(String value, String description){
		this.value = value;
		this.description = description;
	}

	public final String value;
	public final String description;
	
	public String getValue(){
		return value;
	}
	public String getDescription(){
		return description;
	}

}
